# Header
menu:
  ARCHIVES: /archives
  RANDOM: '/categories/Category-1/random/'
  CONTACT: /contact
  ABOUT: /

social:
  twitter:
    url: 'https://twitter.com/'
    class: 'fab fa-twitter'
  github:
    url: 'https://github.com/RandomAdversary/Gradient'
    class: 'fab fa-github'
  bug report:
    url: 'https://github.com/RandomAdversary/Gradient/issues'
    class: 'fas fa-bug'

featured_image: ./img/default.jpg